### ISSUE TITLE
Schema change release 2022-05-16 upgrade

### ISSUE THREAD

**Issue by sfussenegger** [acoustid/mbdata#47]
Add support and upgrade instructions for [2022-05-16 schema change release](https://blog.metabrainz.org/2022/05/16/musicbrainz-schema-change-release-2022-05-16-with-upgrade-instructions/)

```
mbdata.replication.MismatchedSchemaError: Mismatched schema sequence, 26 (database) vs 27 (replication packet)
```

**Comment by sfussenegger** [comment]
I've just tried to apply the update:

    ./scripts/update_sql.sh
    ./scripts/update_models.sh

But the `update_models.sh` script fails:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mbdata/mbdata/tools/genmodels.py", line 542, in <module>
    for line in generate_models_from_sql(tables, types, indexes):
  File "/mbdata/mbdata/tools/genmodels.py", line 361, in generate_models_from_sql
    column_type = map_type(column.type)
  File "/mbdata/mbdata/tools/genmodels.py", line 245, in inner
    raise ValueError('unknown type - ' + type)
ValueError: unknown type - FLUENCY
```
