### ISSUE TITLE
"mbslave sync" command raises exception "AttributeError: 'HTTPResponse' object has no attribute 'name'"

### ISSUE THREAD

**Issue by rayofilluminati** [acoustid/mbdata#56]
After I successfully completed `mbslave init --create-user --create-database` command, which took quite a while, the `mbslave sync` caused an error as following:
```
INFO:mbdata.replication:Downloading https://metabrainz.org/api/musicbrainz/replication-154689.tar.bz2?token=***
Traceback (most recent call last):
  File "/home/m/.local/bin/mbslave", line 8, in <module>
    sys.exit(main())
  File "/home/m/.local/pipx/venvs/mbdata/lib/python3.10/site-packages/mbdata/replication.py", line 803, in main
    args.func(config, args)
  File "/home/m/.local/pipx/venvs/mbdata/lib/python3.10/site-packages/mbdata/replication.py", line 520, in mbslave_sync_main
    process_tar(packet, db, config, ignored_schemas, ignored_tables, schema_seq, replication_seq, hook)
  File "/home/m/.local/pipx/venvs/mbdata/lib/python3.10/site-packages/mbdata/replication.py", line 457, in process_tar
    logger.info("Processing %s", fileobj.name)
AttributeError: 'HTTPResponse' object has no attribute 'name'
```
Take a look at the bottom of the trackback. The exception seems to be raised by logging. So, I commented the logging code out and successfully completed `mbslave sync` command. Hooray!

**Comment by lalinsky** [comment]
Thanks for the report, will fix that.
