### ISSUE TITLE
400: Bad Request Error with mbslave sync

### ISSUE THREAD

**Issue by buckmaxwell** [acoustid/mbdata#9]
Initial db setup worked like a dream. When trying to sync for the firs time, I get a 400. Any thoughts? Here is the full trace

```bash
(mbdata) max@catify-1:~/vendor$ PGPASSWORD=MYPASS mbslave sync
Downloading https://metabrainz.org/api/musicbrainz/replication-126143.tar.bz2
Traceback (most recent call last):
  File "/home/max/vendor/mbdata/bin/mbslave", line 10, in <module>
    sys.exit(main())
  File "/home/max/vendor/mbdata/lib/python3.6/site-packages/mbdata/replication.py", line 592, in main
    args.func(config, args)
  File "/home/max/vendor/mbdata/lib/python3.6/site-packages/mbdata/replication.py", line 466, in mbslave_sync_main
    tmp = download_packet(base_url, token, replication_seq)
  File "/home/max/vendor/mbdata/lib/python3.6/site-packages/mbdata/replication.py", line 437, in download_packet
    data = urlopen(url, timeout=60)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: BAD REQUEST
```

**Comment by heyoni** [comment]
Definitely missing since the API token is normally appended to the end of the URL. For example, my output looks like this:

```
Downloading https://metabrainz.org/api/musicbrainz/replication-132162.tar.bz2?token=REDACTED
Not found, stopping
```

@buckmaxwell make sure your `mbslave.conf` file is in your current directory or setting it with `-c`
